[theme]

base="light"
primaryColor="#60a5fa"
backgroundColor="#fafafa"
textColor="#3f3f46"


# Widgets
showWidgetBorder = true
borderColor = "#eeeef0"

# Base text
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
baseFontWeight = 400
baseFontSize = 14

# Heading text
headingFont = "Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
headingFontWeights = [600, 600, 600, 200, 600, 200]
headingFontSizes = ["3rem", "1.5rem", "1rem", "1rem", "0.8rem", "0.8rem"]





# [theme]
# base = "dark"
# primaryColor = "#FF6B6B"
# backgroundColor = "#0E1117"
# secondaryBackgroundColor = "#262730"
# textColor = "#FAFAFA"